### ISSUE TITLE
ERROR [ExceptionsHandler] Protocol error

### ISSUE THREAD

**Issue by ilhamjaya08** [AlejandroAkbal/Screenshot-API#1]
i got an error when send an request to capture a url, here is the error

[Nest] 11540  - 04/18/2024, 12:54:09 PM   ERROR [ExceptionsHandler] Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters Failed to deserialize params.width - BINDINGS: int32 value expected at position 22
ProtocolError: Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters Failed to deserialize 
params.width - BINDINGS: int32 value expected at position 22
    at Callback.<instance_members_initializer> (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:92:14)
    at new Callback (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:96:16)
    at CallbackRegistry.create (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
    at Connection._rawSend (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:26)
    at CdpCDPSession.send (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
    at EmulatedState.#applyViewport (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/EmulationManager.js:122:32)        
    at EmulatedState.<anonymous> (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:139:23)
    at file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/EmulationManager.js:66:33
    at Array.map (<anonymous>)
    at EmulatedState.sync (file:///C:/Users/RPL%203_24/simple%20api/apps/backend/node_modules/.pnpm/puppeteer-core@21.11.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/EmulationManager.js:65:58)

**Comment by AlejandroAkbal** [comment]
Never seen that issue, make sure you’re using pnpm with node 21, preferably on linux
